{# This file is part of the ISRDI's hlink. #}
{# For copyright and licensing information, see the NOTICE and LICENSE files #}
{# in this project's top-level directory, and also on-line at: #}
{#   https://github.com/ipums/hlink #}

hc.hh_round,
pl.top_a_to_b,
pl.link_type_a1,
pl.link_type_a2,
ra.id as id_a,
hc.NEW_SERIAL_a,
ra.SERIAL as SERIAL_a,
ra.PERNUM as PERNUM_a,
ra.NAMEFRST as NAMEFRST_a,
ra.NAMELAST as NAMELAST_a,
ra.AGE as AGE_a,
ra.BPL as BPL_a,
ra.SEX as SEX_a,
pl.top_b_to_a,
pl.link_type_b1,
pl.link_type_b2,
pl.id_b,
hc.SERIAL_b,
pl.PERNUM_b,
pl.NAMEFRST_b,
pl.NAMELAST_b,
pl.AGE_b,
pl.BPL_b,
pl.SEX_b,
pl.NAMEFRST_UNSTD_a_UNSTD_b_JW,
pl.NAMEFRST_UNSTD_a_STD_b_JW,
pl.NAMEFRST_STD_a_UNSTD_b_JW,
pl.NAMEFRST_STD_a_STD_b_JW,
pl.NAMELAST_JW,
pl.neighbor_ge9_count_close,
pl.neighbor_ge9_count_far,
pl.NAMEFRST_UNSTD2_a,
pl.NAMEFRST_STD_a,
pl.NAMEFRST_UNSTD_a,
pl.NAMEFRST_UNSTD3_a,
pl.NAMEFRST_UNSTD2_b,
pl.NAMEFRST_STD_b,
pl.NAMEFRST_UNSTD_b,
pl.NAMEFRST_UNSTD3_b,
pl.count_a,
pl.count_b,
pl.count_ge9_a,
pl.count_ge9_b,
pl.sum_count,
pl.sum_count_ge9,
pl.race_code_b,
ra.SELF_EMPTY_INFO_RACE as SELF_EMPTY_INFO_RACE_a,
pl.marst_code_b,
pl.rel_gen_b,
pl.rel_det_b,
pl.nuke80_count,
pl.ext80_count,
pl.unrel80_count,
pl.STATE_a,
pl.COUNTY_a,
pl.TOWNSHIP_a,
pl.CITY_a,
pl.stateicp_b,
pl.countyicp_b,
pl.stdcity_coded_b,
pl.stdtownship_coded_b,
pl.SURNAME_SERIAL_a,
pl.SURNAME_ORDER_a,
pl.SURNAME_SIZE_a,
pl.NAMEFRST_MAX_JW,
pl.AGE_DIFF,

hc.close_sum_count as hhf_sum_count,
hc.has_shared_neighbors as hhf_has_shared_neighbors,
hc.unlinked_percent as hhf_unlinked_percent
