name: HLink Docker CI

on: [pull_request, push]

env:
  HLINK_TAG: hlink:githubactions

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $HLINK_TAG-${{ matrix.python_version}} --build-arg PYTHON_VERSION=${{ matrix.python_version }}

    - name: Check dependency versions
      run: |
        docker run $HLINK_TAG-${{ matrix.python_version}} python -V
        echo "Java version:"
        docker run $HLINK_TAG-${{ matrix.python_version}} java -version
    
    - name: Check formatting with black
      run: docker run $HLINK_TAG-${{ matrix.python_version}} black --check .
      
    - name: Lint with flake8
      run: docker run $HLINK_TAG-${{ matrix.python_version}} flake8 --count .
      
    - name: Test
      run: docker run $HLINK_TAG-${{ matrix.python_version}} pytest
    
    - name: Build sdist and wheel
      run: docker run $HLINK_TAG-${{ matrix.python_version}} python -m build
